### ISSUE TITLE
Why read creds as a JSON blob from YAML instead of YAML directly?

### ISSUE THREAD

**Issue by jpmckinney** [little-core-labs/netrc-creds#21]
It'd be nicer to be able to write:

```yaml
creds:
  - machine: github.com
    login: my-user
    password: ${{ secrets.PASSWORD }}
```

**Comment by bcomnes** [comment]
I agree!  Unfortunately GitHub actions (at least at the time of writing) didn't support structured `with` variables. 

https://github.community/t/structured-inputs-input-objects-and-arrays/17783/3

Do you know if it supports that now? 

But now that you bring it up, an alternative API would be that you call netrc-creds multiple times with single entries to add.  

wyt?

**Comment by bcomnes** [comment]
Alternative that COULD work (maybe)

name: Example installing netrc creds


```yml
on: [push]

env:
  - login: l12s-bot

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - uses: little-core-labs/netrc-creds@v2
       with:
         machine: github.com
         login: ${{env.login}}
          password: ${{ secrets.GH_MACHINE_TOKEN }}
    - uses: little-core-labs/netrc-creds@v2
       with:
         machine: api.github.com
         login: ${{env.login}}
          password: ${{ secrets.GH_MACHINE_TOKEN }}
```
